name: 'Deploy theme to Shopify Store'
branding:
  icon: shopping-bag
  colour: green
description: 'Deploys theme to a shopify store'
inputs:
  theme_token:
    description: 'Shopify theme access token'
    required: false
  store:
    description: '<domain>.myshopify.com URL'
    required: false
  theme_root:
    description: 'The root folder for the theme assets that will be uploaded'
    required: false
    default: '.'
  theme_command:
    description: 'Optional command to run instead of `push --development`'
    required: true
  deploy_list_json:
    description: 'JSON string containing stores, themes, and GitHub secrets for deploy passwords'
    required: false
  deploy_template_toml:
    description: 'TOML template string for deployment environments'
    required: false
  cleanup_theme:
    description: 'Whether or not to delete the development theme in a post-action script'
    required: false
    default: 'false'
outputs:
  preview_url:
    description: "The preview url for the deployed theme"
  editor_url:
    description: "The editor url for the deployed theme"
  theme_id:
    description: "The id for the deployed theme"
runs:
  using: 'docker'
  image: 'Dockerfile'
  post-entrypoint: '/post-entrypoint.sh'
