name: 'Deploy theme to Shopify Store'
branding:
  icon: shopping-bag
  colour: green
description: 'Deploys theme to a shopify store'
inputs:
  app_password:
    description: 'Shopify private app password'
    required: true
  store:
    description: '<domain>.myshopify.com URL'
    required: true
  theme_root:
    description: 'The root folder for the theme assets that will be uploaded'
    required: false
    default: '.'
  theme_id:
    description: 'The theme ID to replace'
    required: false
outputs:
  theme_id:
    description: "The theme ID correpsonding to this branch"
  editor_url:
    description: "The editor url for the deployed theme"
  preview_url:
    description: "The preview url for the deployed theme"
runs:
  using: 'docker'
  image: 'Dockerfile'
